#!/bin/bash
#author: qwool, somewhere in december 2021

#a simple resource monitor, abandoned due to slow performance and relying on so many
#packages you would've been better off using btop

#dependencies: sysstat bc

# green_to_red() {
    # r=$(echo $1*2.55 | bc | awk '{print int($1+0.5)}')
    # g=$(echo 255-$1*2.55 | bc | awk '{print int($1+0.5)}')
    # echo "\x1b[38;2;$r;$g;0\nm$r;$g;0\n\x1b[0m\n"
# }
#printf "\x1b[38;2;$(green_to_red 50)mTRUECOLOR\x1b[0m\n"

refreshrate=1

while :; do
    #get info
    ram=$(free -m | awk '/^Mem/ {print $3}')
    totalram=$(free -m | awk '/^Mem/ {print $2}')
    rampct=$(echo $ram*100/$totalram | bc)
    cpu=$(mpstat | awk '$12 ~ /[0-9.]+/ { print 100 - $12"%" }')

    #print and replace
    echo -e " ram: $ram M / $totalram M ($rampct%)"
    echo -e " cpu: $cpu"
    echo -e " refresh rate: $refreshrate sec"
    sleep 1
    for i in {1..3} # change the last number according to how many lines there are
    do
        tput cuu1 # move cursor up by one line
        tput el # clear the line
    done
done
